name: 'Create new Daily Recap'
on:
    schedule:
        # every weekday at 9:00
        - cron: '0 9 * * 1-5'
env:
    NOTION_KEY: ${{ secrets.NOTION_KEY }}
    NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

jobs:
    duplicate_recap:
        name: Create new Document
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '14'
            - run: yarn install

            - name: Build output script
              run: yarn build
            - name: Run built script
              run: node dist/createDailyRecap_viaAPI.js
